TASK_FIRST = 2
REGISTER_ACCOUNTS_QUANTITY = 80
WEBSITE_LOAD_TIME = 45
USER_START_SLEEP = 30
NUMBER_SKIP = 0
FOLLOW_SAVE_VAR = False
MIN_PLAY_TIME = 40
MAX_PLAY_TIME = 120
USE_NORD_VPN = False
USE_MOUSE_DONT_SLEEP = True
NUM_OF_RUNNING_WINDOWS = 3
STREAM_START_NUM = 0
STREAM1_MAX_USER_NUM = 20
STREAM2_MAX_USER_NUM = 40
STREAM3_MAX_USER_NUM = 60
STREAM4_MAX_USER_NUM = 80

